image: Visual Studio 2017

matrix:
  fast_finish: true

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - subnautica-map\node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
  - "%LOCALAPPDATA%\\Yarn"

build_script:
  - ps: ./build.ps1 /m /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /v:n

artifacts:
- path: msbuild.binlog
  name: MSBuild Log
- path: 'subnautica-watcher-release-*.zip'
  name: Release Zip

on_failure:
- appveyor PushArtifact msbuild.binlog
